### ISSUE TITLE
HCCAP brute force

### ISSUE THREAD

**Issue by Maxiz80** [curlyboi/hashtopus#26] opened 2015-09-08 08:47 UTC
Hi.
I don't understand which could be the right procedure to followo to take a brute force attack for and HCCAP file.
I see hashlist (I think reffer to word list).
Can you help me?
Thanks

**Comment by curlyboi** [comment] 2015-11-07 10:09
This is not a bug, closing.
Refer to the manual.

**Closed as completed by curlyboi** 2015-11-07 10:09 UTC
